name: Validate Solution
on:
  workflow_dispatch:
env:
  HACKERRANK_TOKEN: ${{ secrets.SOLUTION_TOKEN }}
  HACKERRANK_STACKS: ${{ vars.HACKERRANK_STACKS }}
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: run script
        uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
      - run: zip -r project.zip . -x '*.git*'
      - run: pip install -r ./.github/scripts/requirements.txt
      - run: python -u ./.github/scripts/validate_solution.py ${{ github.event.repository.name }}
